ccflags-y	+= -I$(srctree)/drivers/power/supply

obj-$(CONFIG_MTK_THERMAL)	+= soc_temp.o
obj-$(CONFIG_MTK_SOC_THERMAL_LVTS)	+= soc_temp_lvts.o
obj-$(CONFIG_MTK_PMIC_THERMAL) += pmic_temp.o
obj-$(CONFIG_MTK_CHARGER_THERMAL) += charger_cooling.o
