subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
subdir-ccflags-y += -I$(srctree)/drivers/power/supply
subdir-ccflags-y += -Werror -I$(srctree)/drivers/usb/typec/pubadc_manage

obj-$(CONFIG_AMZN_LD)  += amzn_ld.o
