#MTK port custom Kbuild
#To Add 1.environment variable
include $(src)/Kbuild-mtk-custom-env

curr := platform/mtk_platform_common

mali_kbase-y += $(curr)/mtk_platform_common.o
mali_kbase-y += $(curr)/mtk_mfg_counter.o
