# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_TYPEC)		+= typec.o
typec-y				:= class.o mux.o bus.o
obj-$(CONFIG_TYPEC)		+= altmodes/
obj-$(CONFIG_TYPEC_TCPM)	+= tcpm/
obj-$(CONFIG_TYPEC_UCSI)	+= ucsi/
obj-$(CONFIG_TYPEC_TPS6598X)	+= tps6598x.o
obj-$(CONFIG_TYPEC)		+= mux/
obj-$(CONFIG_FUSB251)	        += fusb251/
obj-$(CONFIG_MAX20342)	        += max20342/
obj-$(CONFIG_AMZN_LD)	        += amzn_ld/
obj-$(CONFIG_PUBADC_MANAGE)	+= pubadc_manage/
